import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  cardContainer: {
    backgroundColor: "#B2DF01",
    marginHorizontal: 16,
    padding: 16,
    borderRadius: 12,
    shadowColor: "#B2DF01",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 6,
    overflow: "hidden",
    position: "relative",
  },
  topRightCircle: {
    position: "absolute",
    top: -50,
    right: -50,
    width: 200,
    height: 200,
    borderRadius: 100,
    borderWidth: 1,
    borderColor: "#6B8E23",
    opacity: 0.6,
  },
  bottomLeftCircle: {
    position: "absolute",
    bottom: -30,
    left: -30,
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 1,
    borderColor: "#6B8E23",
    opacity: 0.6,
  },
  bottomFarLeftCircle: {
    position: "absolute",
    bottom: -50,
    left: -80,
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 1,
    borderColor: "#6B8E23",
    opacity: 0.6,
  },
  totalContainer: {
    alignItems: "center",
    marginBottom: 24,
  },
  updatedContainer: {
    alignItems: "center",
    marginBottom: 16,
  },
  whiteCard: {
    backgroundColor: "white",
    borderRadius: 8,
    overflow: "hidden",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  incomeSection: {
    flex: 1,
    padding: 12,
    alignItems: "center",
    borderRightWidth: 1,
    borderRightColor: "#E5E5E5",
  },
  expenseSection: {
    flex: 1,
    padding: 12,
    alignItems: "center",
  },
  totalLabel: {
    color: "#262727",
    fontSize: 18,
    marginBottom: 24,
    fontFamily: "PlaywriteDE-Grund",
  },
  totalAmount: {
    color: "#262727",
    fontSize: 45,
    fontWeight: "bold",
    fontFamily: "Winky",
  },
  updatedText: {
    color: "#262727",
    fontSize: 14,
    fontFamily: "PlaywriteDE-Grund",
  },
  incomeLabel: {
    color: "#8aa908",
    fontWeight: "bold",
    fontFamily: "PlaywriteDE-Grund",
    fontSize: 16,
  },
  incomeAmount: {
    fontSize: 16,
    marginTop: 4,
    fontFamily: "PlaywriteDE-Grund",
    fontWeight: "600",
  },
  expenseLabel: {
    color: "#9a161b",
    fontWeight: "bold",
    fontFamily: "PlaywriteDE-Grund",
    fontSize: 16,
  },
  expenseAmount: {
    fontSize: 16,
    marginTop: 4,
    fontFamily: "PlaywriteDE-Grund",
    fontWeight: "600",
  },
});
